name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry source add pytorch --priority=explicit https://download.pytorch.org/whl/cpu
        poetry add --source pytorch torch
        poetry add transformers accelerate
    - name: Run pytest
      run: |
        poetry run pytest
